name: Releases

on: 
  push:
    tags:
    - 'v*'

env:
  CARGO_TERM_COLOR: always
  WORKSPACE_DIR: ./rust_ws

jobs:
  publish:
    strategy:
      matrix:
        platform:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            ext: ''
            suffix: linux-x86_64
          - os: ubuntu-latest
            target: aarch64-unknown-linux-musl
            ext: ''
            suffix: linux-arm64
          - os: macos-latest
            target: aarch64-apple-darwin
            ext: ''
            suffix: mac-arm64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            ext: .exe
            suffix: win-x86_64
    runs-on: ${{ matrix.platform.os }}
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Install target
      shell: bash
      run: |
        if ! rustup target list --installed | grep -q '^${{ matrix.platform.target }}$'; then
          rustup target add ${{ matrix.platform.target }}
        fi
    - name: Build (Release)
      run: cargo build --release --manifest-path ${{ env.WORKSPACE_DIR }}/Cargo.toml --target ${{ matrix.platform.target }}
    - uses: ncipollo/release-action@v1
      with:
        artifacts: ${{ env.WORKSPACE_DIR }}/target/release/gha_test${{ matrix.platform.ext }}
        generateReleaseNotes: true
