name: Run Tests

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
    # runs-on: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Run tests (Debug)
      run: cargo test --manifest-path rust_ws/Cargo.toml
    - name: Run tests (Release)
      run: cargo test --release --manifest-path rust_ws/Cargo.toml

  # test-mac:
  #   runs-on: macos-latest
  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Run tests (Debug)
  #     run: cargo test --manifest-path rust_ws/Cargo.toml
  #   - name: Run tests (Release)
  #     run: cargo test --release --manifest-path rust_ws/Cargo.toml

  # test-windows:
  #   runs-on: windows-latest
  #   steps:
  #   - uses: actions/checkout@v4
  #   - name: Run tests (Debug)
  #     run: cargo test --manifest-path rust_ws/Cargo.toml
  #   - name: Run tests (Release)
  #     run: cargo test --release --manifest-path rust_ws/Cargo.toml
