name: Run Tests

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run tests (Debug)
      run: cargo test --manifest-path rust_ws/Cargo.toml
    - name: Run tests (Release)
      run: cargo test --release --manifest-path rust_ws/Cargo.toml
