name: Run Tests

on:
  push:
    branches:
      - main
      - dev
    paths:
      - rust_ws/**
  pull_request:
    branches:
      - main
      - dev
    paths:
      - rust_ws/**

env:
  CARGO_TERM_COLOR: always
  WORKING_DIR: ./rust_ws

jobs:
  test:
    strategy:
      matrix:
        platform:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            cross: false
          - os: ubuntu-latest
            target: aarch64-unknown-linux-musl
            cross: true
          - os: macos-latest
            target: aarch64-apple-darwin
            cross: false
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            cross: false
    runs-on: ${{ matrix.platform.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/cache_cargo
      with:
        target: ${{ matrix.platform.target }}
        workspace: ${{ env.WORKING_DIR }}
    - name: Run tests (Debug)
      run: cargo test --manifest-path ${{ env.WORKING_DIR }}/Cargo.toml
    - name: Run tests (Release)
      run: cargo test --release --manifest-path ${{ env.WORKING_DIR }}/Cargo.toml
