name: Run Tests

on:
  push:
    branches:
      - main
      - dev
    paths:
      - rust_ws/**
  pull_request:
    branches:
      - main
      - dev
    paths:
      - rust_ws/**

env:
  CARGO_TERM_COLOR: always
  WORKING_DIR: ./rust_ws

jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Cache cargo registry
      uses: actions/cache@v1
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles(format('{0}/Cargo.lock', env.WORKING_DIR)) }}
    - name: Cache cargo index
      uses: actions/cache@v1
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles(format('{0}/Cargo.lock', env.WORKING_DIR)) }}
    - name: Cache cargo build
      uses: actions/cache@v1
      with:
        path: ${{ env.WORKING_DIR }}/target/
        key: ${{ runner.os }}-cargo-build-target-${{ hashFiles(format('{0}/Cargo.lock', env.WORKING_DIR)) }}
    - name: Run tests (Debug)
      run: cargo test --manifest-path ${{ env.WORKING_DIR }}/Cargo.toml
    - name: Run tests (Release)
      run: cargo test --release --manifest-path ${{ env.WORKING_DIR }}/Cargo.toml
